backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: projects
    label: Projects
    files:

      - name: cave-network
        label: Cave Network
        file: images/cave-network/info.json
        fields:
          - { name: title,       label: Title,       widget: string }
          - { name: year,        label: Year,        widget: string, required: false }
          - { name: medium,      label: Medium,      widget: string, required: false }
          - { name: description, label: Description, widget: text,   required: false }
          - name: cover
            label: Cover Image
            widget: image
            required: false
            media_folder: /images/cave-network
            public_folder: images/cave-network

      - name: physical-works
        label: Physical Works
        file: images/physical-works/info.json
        fields:
          - { name: title,       label: Title,       widget: string }
          - { name: year,        label: Year,        widget: string, required: false }
          - { name: medium,      label: Medium,      widget: string, required: false }
          - { name: description, label: Description, widget: text,   required: false }
          - name: cover
            label: Cover Image
            widget: image
            required: false
            media_folder: /images/physical-works
            public_folder: images/physical-works

      - name: ascii-art
        label: ASCII Art
        file: images/ascii-art/info.json
        fields:
          - { name: title,       label: Title,       widget: string }
          - { name: year,        label: Year,        widget: string, required: false }
          - { name: medium,      label: Medium,      widget: string, required: false }
          - { name: description, label: Description, widget: text,   required: false }
          - name: cover
            label: Cover Image
            widget: image
            required: false
            media_folder: /images/ascii-art
            public_folder: images/ascii-art

      - name: 1bit
        label: 1bit
        file: images/1bit/info.json
        fields:
          - { name: title,       label: Title,       widget: string }
          - { name: year,        label: Year,        widget: string, required: false }
          - { name: medium,      label: Medium,      widget: string, required: false }
          - { name: description, label: Description, widget: text,   required: false }
          - name: cover
            label: Cover Image
            widget: image
            required: false
            media_folder: /images/1bit
            public_folder: images/1bit

      - name: lights-series
        label: Lights Series
        file: images/lights-series/info.json
        fields:
          - { name: title,       label: Title,       widget: string }
          - { name: year,        label: Year,        widget: string, required: false }
          - { name: medium,      label: Medium,      widget: string, required: false }
          - { name: description, label: Description, widget: text,   required: false }
          - name: cover
            label: Cover Image
            widget: image
            required: false
            media_folder: /images/lights-series
            public_folder: images/lights-series

      - name: architectures
        label: Architectures
        file: images/architectures/info.json
        fields:
          - { name: title,       label: Title,       widget: string }
          - { name: year,        label: Year,        widget: string, required: false }
          - { name: medium,      label: Medium,      widget: string, required: false }
          - { name: description, label: Description, widget: text,   required: false }
          - name: cover
            label: Cover Image
            widget: image
            required: false
            media_folder: /images/architectures
            public_folder: images/architectures
